global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    - seata-server:9898
- job_name: account_service_db_exporter
  static_configs:
  - targets: ['account-service-db-exporter:9104']    
- job_name: order_service_db_exporter
  static_configs:
  - targets: ['order-service-db-exporter:9104']    
- job_name: storage_service_db_exporter
  static_configs:
  - targets: ['storage-service-db-exporter:9104']    
